### ISSUE TITLE
iPad version not detecting all books, only 9

### ISSUE THREAD

**Issue by chrisnyc97** [loledeck/librairie.cubesoft.fr#4]
I have the full featured paid version. It is not detecting all the books I have on my google drive. It stops at 9 books. It should see 21. I reset the database. Unlinked and relinked my account. No luck.

**Comment by loledeck** [comment]
Hello,

I assume (based on your handle) that the GDrive account you’re syncing with the app is chrisnyc@[REDACTED]. If this is not the case please, give me the correct account so that I can look into your problem.

I’ve relaunched a full sync from your account, it ran without error and found again 9 ebooks. 

My guess is that your other ebooks are probably PDFs files. Please note that the PDF files are not synced automatically, only ePub, mobi and azw(3) files are. PDF files have to be added manually. The reason is that the overwhelming majority of the pdfs stored in cloud accounts are not ebooks but mundane stuffs such as receipts, web prints, invoices … and importing them automatically would completely clutter user libraries.

Best,
Laurent


Le 11 février 2018 à 04:08:05, chrisnyc97 (notifications@github.com) a écrit:

I have the full featured paid version. It is not detecting all the books I have on my google drive. It stops at 9 books. It should see 21. I reset the database. Unlinked and relinked my account. No luck.

**Comment by chrisnyc97** [comment]
That worked. Thank you. I didn’t notice there is a browse button.
